export interface Country {
  name: string;
  code: string;
}

export const countries: Country[] = [
  { name: 'United States', code: 'US' },
  { name: 'China', code: 'CN' },
  { name: 'India', code: 'IN' },
  { name: 'Brazil', code: 'BR' },
  { name: 'Russia', code: 'RU' },
  { name: 'Japan', code: 'JP' },
  { name: 'Germany', code: 'DE' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'France', code: 'FR' },
  { name: 'Italy', code: 'ITA' },
  { name: 'Canada', code: 'CA' },
  { name: 'Australia', code: 'AU' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Spain', code: 'ES' },
  { name: 'South Korea', code: 'KR' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Argentina', code: 'AR' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'Egypt', code: 'EG' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Vietnam', code: 'VN' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Iran', code: 'IR' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Israel', code: 'IL' },
  { name: 'Greece', code: 'GR' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Norway', code: 'NO' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Finland', code: 'FI' },
  { name: 'Poland', code: 'PL' },
  { name: 'Austria', code: 'AT' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Czech Republic', code: 'CZ' },
  { name: 'Chile', code: 'CL' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Peru', code: 'PE' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'Romania', code: 'RO' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Serbia', code: 'RS' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Iceland', code: 'IS' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Andorra', code: 'AD' },
  { name: 'San Marino', code: 'SM' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Malta', code: 'MT' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Qatar', code: 'QA' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Oman', code: 'OM' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Tanzania', code: 'TZ' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Ivory Coast', code: 'CI' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Angola', code: 'AO' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Zimbabwe', code: 'ZW' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Syria', code: 'SY' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'North Korea', code: 'KP' },
  { name: 'South Korea', code: 'KR' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Laos', code: 'LA' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Brunei', code: 'BN' },
  { name: 'Papua New Guinea', code: 'PG' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Samoa', code: 'WS' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Solomon Islands', code: 'SB' },
  { name: 'Marshall Islands', code: 'MH' },
  { name: 'Micronesia', code: 'FM' },
  { name: 'Palau', code: 'PW' },
];